// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoZmB-i-XsRO9XCUaNg-IM0a2GQuyCIAQ',
    appId: '1:179298492994:web:dc49501df3fe642b9343db',
    messagingSenderId: '179298492994',
    projectId: 'flutter-catalog-9703c',
    authDomain: 'flutter-catalog-9703c.firebaseapp.com',
    storageBucket: 'flutter-catalog-9703c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1QBD-ayWjITbEtdox-2KG6sc6V7QRfMk',
    appId: '1:179298492994:android:1eb6a70bd4178d459343db',
    messagingSenderId: '179298492994',
    projectId: 'flutter-catalog-9703c',
    storageBucket: 'flutter-catalog-9703c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuurxxy2eKp7atJZZofnSD_435jNGoK5I',
    appId: '1:179298492994:ios:3a06958afa8063b79343db',
    messagingSenderId: '179298492994',
    projectId: 'flutter-catalog-9703c',
    storageBucket: 'flutter-catalog-9703c.firebasestorage.app',
    iosBundleId: 'com.example.flutterCatalog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuurxxy2eKp7atJZZofnSD_435jNGoK5I',
    appId: '1:179298492994:ios:3a06958afa8063b79343db',
    messagingSenderId: '179298492994',
    projectId: 'flutter-catalog-9703c',
    storageBucket: 'flutter-catalog-9703c.firebasestorage.app',
    iosBundleId: 'com.example.flutterCatalog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoZmB-i-XsRO9XCUaNg-IM0a2GQuyCIAQ',
    appId: '1:179298492994:web:c85be963574f45ba9343db',
    messagingSenderId: '179298492994',
    projectId: 'flutter-catalog-9703c',
    authDomain: 'flutter-catalog-9703c.firebaseapp.com',
    storageBucket: 'flutter-catalog-9703c.firebasestorage.app',
  );
}
